package mps.demo.calc.sandbox;

/*Generated by MPS */

import mps.demo.calc.runtime.BaseCalculator;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.BorderLayout;

public class test extends BaseCalculator {
  public test() {
    super("test");

    {
      JPanel digits = new JPanel(new GridLayout(0, 3, 10, 10));
      for (char digit : new char[]{'7', '8', '9', '4', '5', '6', '1', '2', '3', '0', '.'}) {
        digits.add(new BaseCalculator.Digit(digit + "", digit));
      }
      add(digits, BorderLayout.WEST);
    }
  }



  public static void main(String[] args) {
    new test();
  }
}
