package mps.demo.calc.sandbox;

/*Generated by MPS */

import mps.demo.calc.runtime.BaseCalculator;
import javax.swing.JPanel;
import java.awt.GridLayout;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import mps.demo.calc.runtime.CalcStatus;
import java.awt.BorderLayout;

public class trigonometry extends BaseCalculator {
  public trigonometry() {
    super("trigonometry");

    JPanel userOps = new JPanel(new GridLayout(0, 1, 10, 10));

    userOps.add(new BaseCalculator.UnOp("sin", new _FunctionTypes._return_P1_E0<Double, Double>() {
      public Double invoke(Double x) {
        return Math.sin(x);
      }
    }));
    userOps.add(new BaseCalculator.NulOp("arc", new _FunctionTypes._return_P0_E0<Double>() {
      public Double invoke() {
        
        CalcStatus.getCalcStatus().setStatus("arc", !((Boolean) CalcStatus.getCalcStatus().getStatus("arc")));;
        return 0.0;
      }
    }));
    add(userOps, BorderLayout.EAST);
    setSize(300, 300);
  }



  public static void main(String[] args) {
    new trigonometry();
  }
}
