package mps.demo.calc.sandbox;

/*Generated by MPS */

import mps.demo.calc.runtime.BaseCalculator;

public class trigonometry extends BaseCalculator {
  public trigonometry() {
    super("trigonometry");

  }



  public static void main(String[] args) {
    new trigonometry();
  }
}
