package mps.demo.calc.sandbox;

/*Generated by MPS */

import mps.demo.calc.runtime.BaseCalculator;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.BorderLayout;

public class trigonometry extends BaseCalculator {
  public trigonometry() {
    super("trigonometry");

    {
      JPanel digits = new JPanel(new GridLayout(0, 3, 10, 10));/* error: statement w/o textGen:foreach */
      add(digits, BorderLayout.WEST);
    }
  }



  public static void main(String[] args) {
    new trigonometry();
  }
}
