package pow.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Pow_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Pow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "pow.structure.Pow";
  }
}
