package Shapes.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_8842926895971870741(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971863778(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971917726(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "x");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971919445(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "y");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971921228(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "radius");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971923077(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "radius");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971936309(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "upperLeftX");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971938059(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "upperLeftY");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971939662(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "size");
  }

  public static Object propertyMacro_GetPropertyValue_8842926895971941317(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "size");
  }

  public static Object referenceMacro_GetReferent_8842926895971925361(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "color", true), "color", false);
  }

  public static Object referenceMacro_GetReferent_8842926895971944329(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "color", true), "color", false);
  }

  public static Iterable<SNode> sourceNodesQuery_8842926895971874740(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "shapes", true);
  }
}
