package TraceAspect.lang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TracingEntity {
  Assignments("Assignments", "assignment"),
  Method_calls("Method calls", "calls"),
  Return_from_method("Return from method", "return");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TracingEntity> getConstants() {
    List<TracingEntity> list = ListSequence.fromList(new LinkedList<TracingEntity>());
    ListSequence.fromList(list).addElement(TracingEntity.Assignments);
    ListSequence.fromList(list).addElement(TracingEntity.Method_calls);
    ListSequence.fromList(list).addElement(TracingEntity.Return_from_method);
    return list;
  }

  public static TracingEntity getDefault() {
    return null;
  }

  public static TracingEntity parseValue(String value) {
    if (value == null) {
      return TracingEntity.getDefault();
    }
    if (value.equals(TracingEntity.Assignments.getValueAsString())) {
      return TracingEntity.Assignments;
    }
    if (value.equals(TracingEntity.Method_calls.getValueAsString())) {
      return TracingEntity.Method_calls;
    }
    if (value.equals(TracingEntity.Return_from_method.getValueAsString())) {
      return TracingEntity.Return_from_method;
    }
    return TracingEntity.getDefault();
  }

  private String myValue;

  TracingEntity(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
