package Schedule.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.UUID;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptEducationalDay = new ConceptDescriptorBuilder("Schedule.structure.EducationalDay", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293498013L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).childDescriptors(new ConceptDescriptorBuilder.Link(2730820940293503804L, "lectures", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293501673L), true, true, false)).children(new String[]{"lectures"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptLecture = new ConceptDescriptorBuilder("Schedule.structure.Lecture", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293501673L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2730820940293503881L, "room"), new ConceptDescriptorBuilder.Prop(2730820940293503896L, "presenter")).properties("room", "presenter").childDescriptors(new ConceptDescriptorBuilder.Link(2730820940293503839L, "timeStart", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293503813L), false, false, false), new ConceptDescriptorBuilder.Link(2730820940293503841L, "timeFinish", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293503813L), false, false, false)).children(new String[]{"timeStart", "timeFinish"}, new boolean[]{false, false}).create();
  /*package*/ final ConceptDescriptor myConceptSchedule = new ConceptDescriptorBuilder("Schedule.structure.Schedule", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293372535L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).childDescriptors(new ConceptDescriptorBuilder.Link(2730820940293498023L, "days", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293498013L), true, true, false)).children(new String[]{"days"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptTime = new ConceptDescriptorBuilder("Schedule.structure.Time", MetaIdFactory.conceptId(UUID.fromString("a2c55519-5234-4e83-b8f8-06b09652be8e"), 2730820940293503813L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2730820940293503822L, "hours"), new ConceptDescriptorBuilder.Prop(2730820940293503824L, "minutes")).properties("hours", "minutes").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEducationalDay, myConceptLecture, myConceptSchedule, myConceptTime);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0i, conceptFqName)) {
      case 0:
        return myConceptEducationalDay;
      case 1:
        return myConceptLecture;
      case 2:
        return myConceptSchedule;
      case 3:
        return myConceptTime;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0i = new String[]{"Schedule.structure.EducationalDay", "Schedule.structure.Lecture", "Schedule.structure.Schedule", "Schedule.structure.Time"};
}
