/*
 * generated by Xtext
 */
package ru.spbau.turaev.depgraph.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ru.spbau.turaev.depgraph.ui.internal.MyDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyDslActivator.getInstance().getInjector(MyDslActivator.RU_SPBAU_TURAEV_DEPGRAPH_MYDSL);
	}
	
}
