/*
 * generated by Xtext
 */
package ru.spbau.turaev.depgraph.ui.contentassist

import ru.spbau.turaev.depgraph.ui.contentassist.AbstractMyDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
