package mps.demo.calc.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("mps.demo.calc.structure.Calculator").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.execution.util.structure.IMainClass").properties("datatype", "digits", "memory", "stdOps").children(new String[]{"userFun", "ui"}, new boolean[]{true, false}).create();
      case 1:
        return new ConceptDescriptorBuilder("mps.demo.calc.structure.GetStatusExpression").super_("jetbrains.mps.baseLanguage.structure.Expression").parents("jetbrains.mps.baseLanguage.structure.Expression").properties("key").alias("status.", "").create();
      case 2:
        return new ConceptDescriptorBuilder("mps.demo.calc.structure.SetStatusExpression").super_("jetbrains.mps.baseLanguage.structure.Expression").parents("jetbrains.mps.baseLanguage.structure.Expression").properties("key").children(new String[]{"value"}, new boolean[]{false}).alias("status =", "").create();
      case 3:
        return new ConceptDescriptorBuilder("mps.demo.calc.structure.UI").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("fontSize", "groupDigits").create();
      case 4:
        return new ConceptDescriptorBuilder("mps.demo.calc.structure.UserFunction").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("label").children(new String[]{"function"}, new boolean[]{false}).create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"mps.demo.calc.structure.Calculator", "mps.demo.calc.structure.GetStatusExpression", "mps.demo.calc.structure.SetStatusExpression", "mps.demo.calc.structure.UI", "mps.demo.calc.structure.UserFunction"};
}
