package pow.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;

public class Name {
  public static void main(String[] args) {
    double d = Math.pow(3, 2.3);
    double result = Math.pow(2, d);
    System.out.println("value = " + result);
    List<Integer> a = ListSequence.fromList(new ArrayList<Integer>());
    ListSequence.fromList(a).where(new IWhereFilter<Integer>() {
      public boolean accept(Integer it) {
        return it > 3;
      }
    });
  }
}
