package stopwatch.lang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum ButtonActionType {
  Start("Start", "start"),
  Pause("Pause", "pause"),
  Reset("Reset", "reset"),
  Circle("Circle", "circle");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<ButtonActionType> getConstants() {
    List<ButtonActionType> list = ListSequence.fromList(new LinkedList<ButtonActionType>());
    ListSequence.fromList(list).addElement(ButtonActionType.Start);
    ListSequence.fromList(list).addElement(ButtonActionType.Pause);
    ListSequence.fromList(list).addElement(ButtonActionType.Reset);
    ListSequence.fromList(list).addElement(ButtonActionType.Circle);
    return list;
  }

  public static ButtonActionType getDefault() {
    return null;
  }

  public static ButtonActionType parseValue(String value) {
    if (value == null) {
      return ButtonActionType.getDefault();
    }
    if (value.equals(ButtonActionType.Start.getValueAsString())) {
      return ButtonActionType.Start;
    }
    if (value.equals(ButtonActionType.Pause.getValueAsString())) {
      return ButtonActionType.Pause;
    }
    if (value.equals(ButtonActionType.Reset.getValueAsString())) {
      return ButtonActionType.Reset;
    }
    if (value.equals(ButtonActionType.Circle.getValueAsString())) {
      return ButtonActionType.Circle;
    }
    return ButtonActionType.getDefault();
  }

  private String myValue;

  ButtonActionType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
