package stopwatch.lang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Form {
  square_form("square form", "square"),
  circle_form("circle form", "circle");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Form> getConstants() {
    List<Form> list = ListSequence.fromList(new LinkedList<Form>());
    ListSequence.fromList(list).addElement(Form.square_form);
    ListSequence.fromList(list).addElement(Form.circle_form);
    return list;
  }

  public static Form getDefault() {
    return null;
  }

  public static Form parseValue(String value) {
    if (value == null) {
      return Form.getDefault();
    }
    if (value.equals(Form.square_form.getValueAsString())) {
      return Form.square_form;
    }
    if (value.equals(Form.circle_form.getValueAsString())) {
      return Form.circle_form;
    }
    return Form.getDefault();
  }

  private String myValue;

  Form(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
