package stopwatch.lang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum StopwatchType {
  Quartz_stopwatch("Quartz stopwatch", "digital"),
  Mechanical_stopwatch("Mechanical stopwatch", "analog");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<StopwatchType> getConstants() {
    List<StopwatchType> list = ListSequence.fromList(new LinkedList<StopwatchType>());
    ListSequence.fromList(list).addElement(StopwatchType.Quartz_stopwatch);
    ListSequence.fromList(list).addElement(StopwatchType.Mechanical_stopwatch);
    return list;
  }

  public static StopwatchType getDefault() {
    return null;
  }

  public static StopwatchType parseValue(String value) {
    if (value == null) {
      return StopwatchType.getDefault();
    }
    if (value.equals(StopwatchType.Quartz_stopwatch.getValueAsString())) {
      return StopwatchType.Quartz_stopwatch;
    }
    if (value.equals(StopwatchType.Mechanical_stopwatch.getValueAsString())) {
      return StopwatchType.Mechanical_stopwatch;
    }
    return StopwatchType.getDefault();
  }

  private String myValue;

  StopwatchType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
