package stopwatch.lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.Appearance").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").properties("form", "width", "height", "weigth").children(new String[]{"color"}, new boolean[]{false}).create();
      case 1:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.Button").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"actions"}, new boolean[]{true}).alias("", "\u043a\u043d\u043e\u043f\u043a\u0430 \u043d\u0430 \u0441\u0435\u043a\u0443\u043d\u0434\u043e\u043c\u0435\u0440\u0435").create();
      case 2:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.ButtonAction").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("caption").create();
      case 3:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.ColorReference").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("color").create();
      case 4:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.Stopwatch").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").properties("url", "type", "circleTimes").children(new String[]{"maximumOperatingTime", "timelines", "buttons", "appearance"}, new boolean[]{false, true, true, false}).create();
      case 5:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.Time").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("value", "unit").alias("", "\u0432\u0440\u0435\u043c\u044f").create();
      case 6:
        return new ConceptDescriptorBuilder("stopwatch.lang.structure.Timeline").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"accuracy", "rolloverTime"}, new boolean[]{false, false}).alias("", "\u0448\u043a\u0430\u043b\u0430 \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u043d\u0430 \u0441\u0435\u043a\u0443\u043d\u0434\u043e\u043c\u0435\u0440\u0435").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"stopwatch.lang.structure.Appearance", "stopwatch.lang.structure.Button", "stopwatch.lang.structure.ButtonAction", "stopwatch.lang.structure.ColorReference", "stopwatch.lang.structure.Stopwatch", "stopwatch.lang.structure.Time", "stopwatch.lang.structure.Timeline"};
}
