package TraceAspect.lang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LogFormat_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public LogFormat_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TraceAspect.lang.structure.LogFormat";
  }
}
