package TraceAspect.lang.sandbox;

/*Generated by MPS */

import TraceAspect.lang.runtime.Tracer;

public class MainClass {
  /*package*/ int n = 6;


  public MainClass() {
    Tracer.traceVoidReturn("MainClass");
  }



  public MainClass(int v) {
    n = Tracer.traceAssignment("n", v);
    Tracer.traceVoidReturn("MainClass");
  }



  /*package*/ int assignments(String s) {
    int k;
    s = Tracer.traceAssignment("s", "test2");
    n = Tracer.traceAssignment("n", 8);
    this.n = Tracer.traceAssignment("MainClass.n", 19);
    k = Tracer.traceAssignment("k", n + Tracer.traceCall(s, "s", "length").length());

    voidMethod();

    return Tracer.traceNonVoidReturn("assignments", 3232);
  }



  /*package*/ void voidMethod() {
    Tracer.traceCall(System.out, "out", "println").println("We're inside void method");
    Tracer.traceVoidReturn("voidMethod");
  }



  public static void main(String[] args) {
    MainClass a = Tracer.traceConstructor(new MainClass(), "a", "MainClass");
    Tracer.traceCall(a, "a", "assignments").assignments("qwerty");

    MainClass b = Tracer.traceConstructor(new MainClass(142), "b", "MainClass");
    Tracer.traceCall(b, "b", "voidMethod").voidMethod();
    Tracer.traceVoidReturn("main");
  }


}
