package demo.trace.aspect.runtime;

/*Generated by MPS */


public class Tracer {
  public static <T> T trace(String name, T value) {
    System.out.println("assignment to " + name + " value = " + value);
    return value;
  }
}
