package Schedule.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.BaseHelginsDescriptor;
import jetbrains.mps.lang.typesystem.runtime.ComparisonRule_Runtime;

public class TypesystemDescriptor extends BaseHelginsDescriptor {
  public TypesystemDescriptor() {
    {
      ComparisonRule_Runtime comparisonRule = new TimeCompare_ComparisonRule();
      this.myComparisonRules.add(comparisonRule);
    }
  }
}
