/*
 * generated by Xtext
 */
package ru.spbau.turaev.depgraph;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends ru.spbau.turaev.depgraph.AbstractMyDslRuntimeModule {

}
