package stopwatch.lang.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 4:
        return new Stopwatch_BehaviorDescriptor();
      case 6:
        return new Timeline_BehaviorDescriptor();
      case 5:
        return new Time_BehaviorDescriptor();
      case 1:
        return new Button_BehaviorDescriptor();
      case 2:
        return new ButtonAction_BehaviorDescriptor();
      case 0:
        return new Appearance_BehaviorDescriptor();
      case 3:
        return new ColorReference_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"stopwatch.lang.structure.Appearance", "stopwatch.lang.structure.Button", "stopwatch.lang.structure.ButtonAction", "stopwatch.lang.structure.ColorReference", "stopwatch.lang.structure.Stopwatch", "stopwatch.lang.structure.Time", "stopwatch.lang.structure.Timeline"};
}
