package stopwatch.lang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ButtonAction_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ButtonAction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stopwatch.lang.structure.ButtonAction";
  }
}
