/*
* generated by Xtext
*/
package ru.spbau.turaev.depgraph;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ru.spbau.turaev.depgraph.ui.internal.MyDslActivator.getInstance().getInjector("ru.spbau.turaev.depgraph.MyDsl");
	}
	
}
