package demo.trace.aspect.sandbox;

/*Generated by MPS */

import demo.trace.aspect.runtime.Tracer;

public class Test {
  /*package*/ int n = 6;

  /*package*/ void f(String p) {
    p = Tracer.trace("p", "test1");
    n = Tracer.trace("n", 8);
    this.n = Tracer.trace("Test.n", 9);
  }



  public static void main(String[] args) {
    new Test().f("asdf");
  }
}
