package mps.demo.calc.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class GetStatusExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public GetStatusExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mps.demo.calc.structure.GetStatusExpression";
  }
}
