package mps.demo.calc.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class SetStatusExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SetStatusExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mps.demo.calc.structure.SetStatusExpression";
  }
}
