package mps.demo.calc.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class SetStatusExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isLegalAsStatement_1239211900844(SNode thisNode) {
    return true;
  }
}
