package mps.demo.calc.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class SetStatusExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SetStatusExpression_BehaviorDescriptor() {
  }

  public boolean virtual_isLegalAsStatement_1239211900844(SNode thisNode) {
    return SetStatusExpression_Behavior.virtual_isLegalAsStatement_1239211900844(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "mps.demo.calc.structure.SetStatusExpression";
  }
}
