package mps.demo.calc.runtime;

/*Generated by MPS */

import javax.swing.JFrame;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class BaseCalculator extends JFrame {
  private double value1;
  private double value2;
  private _FunctionTypes._return_P2_E0<? extends Double, ? super Double, ? super Double> curOp = null;

  private String input = "";

  private final JLabel indicator = new JLabel("0");


  public BaseCalculator(String title) {
    setTitle(title);
    setLayout(new BorderLayout());
    add(indicator, BorderLayout.NORTH);

    setDefaultCloseOperation(EXIT_ON_CLOSE);
    setVisible(true);
  }



  public class Digit extends JButton {
    public Digit(String label, final char value) {
      super(label);
      addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent p0) {
          input += value;
        }
      });
    }
  }
}
